[env]
_.path = ["{{config_root}}/bin"]

# Database configuration
PGDATABASE = "tpr_dev"
TEST_DATABASE = "tpr_test"

# TEST_DATABASE_COUNT is how many test databases to use. Each database test has exclusive use of a database while it is
# executing so this number is also the maximum number of database tests that can execute in parallel.
TEST_DATABASE_COUNT = "8"

# Test browser configuration
TESTBROWSER_MAX_CONCURRENT_TESTS = "4"

# Tern migration configuration
TERN_CONFIG = "postgresql/tern.conf"
TERN_MIGRATIONS = "postgresql/migrations"

TESTBROWSER_CHROME_BINARY = "{{env.HOME}}/.cache/ms-playwright/chromium-1200/chrome-linux/chrome"

# Production configuration
# PRODUCTION_HOST = "example.com"

[tools]
go = '1.25.6'
nodejs = '22.20.0'
ruby = '4.0.1'
